apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ce-replykit
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: ko://github.com/odacremolbap/ce-replykit
        env:
        - name: CE_REPLY_KIT_STORAGE_TTL_SECONDS
          value: "300"

